apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shopping

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: suresh628/shop-backend:v2
        ports:
        - containerPort: 3000

        env:
        - name: POSTGRES_HOST
          value: "postgres"

        - name: POSTGRES_PORT
          value: "5432"

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
